libreria/urls.py
from django.urls import path

from .views import AutoreDetailCBV, LibroListCBV

urlpatterns = [
    path('', LibroListCBV.as_view(), name='lista_libri'),
    path('autore/<int:pk>/', AutoreDetailCBV.as_view(), name='profilo_autore')
]

news/urls.py
from django.urls import path
from.views import home, ArticoloDetailViewCB, ArticoloListView, GiornalistaDetailViewCB,GiornalistaListView #articoloDetailView
app_name="news"
urlpatterns= [
    path('',home,name="homeview"),
    #path("articoli//<int:pk>", articoloDetailView, name="articolo_detail")
    path("articoli/<int:pk>", ArticoloDetailViewCB.as_view(), name="articolo_detail"),
    path("lista_articoli/", ArticoloListView.as_view(), name="lista_articoli"),
    path("giornalista/<int:pk>", GiornalistaDetailViewCB.as_view(),
         name="giornalista_detail"),
    path("lista_giornalisti/", GiornalistaListView.as_view(),
         name="lista_giornalisti")
    
]

prima_app/urls.py
from django.urls import path
from .views import homepage, menu, chisiamo, variabili,index
app_name='prima_app'
urlpatterns = [
    path('welcome/', homepage, name='home'),
    path('menu/', menu, name='menu'),
    path('chisiamo/', chisiamo, name='chisiamo'),
    path('variabili/', variabili, name='variabili'),
    path('index/', index, name='index'),
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path, include
from prima_app.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index,name='index'),
    path('prima_app/', include('prima_app.urls')),
    path('seconda_app/', include('seconda_app.urls')),
     path('news/', include('news.urls')),
     path('libreria/', include('libreria.urls'))
   
]

seconda_app/urls.py
  
from django.urls import path
from .views import esempio_if,esempio_ifelse, esempio_elif, esempio_for
app_name = 'seconda_app'
urlpatterns = [
    path('if', esempio_if, name='if'),
    path('ifelse', esempio_ifelse, name='ifelse'),
    path('ifelif', esempio_elif, name='elif'),
    path('for', esempio_for, name='for'),
]

libreria/models.py
from django.db import models
    
class Genere_ArducaDiego(models.Model):
    nome= models.CharField(max_length=20)

    def __str__(self):
        return self.nome 
    
    class Meta:
        verbose_name="Genere"
        verbose_name_plural="Generi"

class Autore_ArducaDiego(models.Model):
    nome= models.CharField(max_length=20)
    cognome= models.CharField(max_length=20) 

    def __str__(self):
        return self.nome + " " + self.cognome

    class Meta:
        verbose_name="Autore"
        verbose_name_plural="Autori"
        
    

class Libro_ArducaDiego(models.Model):
    titolo= models.CharField(max_length=20)
    autore= models.ForeignKey(Autore_ArducaDiego, on_delete=models.CASCADE, related_name="libri")
    genere = models.ManyToManyField(Genere_ArducaDiego)

    def __str__(self):
        return self.titolo

    class Meta:
        verbose_name="Libro"
        verbose_name_plural="Libri"

news/models.py
from django.db import models

class Giornalista(models.Model):
    nome= models.CharField(max_length=20)
    cognome= models.CharField(max_length=20)

    def __str__(self):
        return self.nome + " " + self.cognome
    class Meta:
        verbose_name="Giornalista"
        verbose_name_plural="Giornalisti"

class Articolo (models.Model):
    titolo= models.CharField(max_length=100)
    contenuto= models.TextField()
    giornalista= models.ForeignKey(Giornalista, on_delete=models.CASCADE, related_name="articoli")

    def __str__(self):
        return self.titolo
    class Meta:
        verbose_name="Articolo"
        verbose_name_plural="Articoli"

prima_app/models.py
from django.db import models

# Create your models here.

seconda_app/models.py
from django.db import models

# Create your models here.

libreria/views.py
from django.shortcuts import render
from .models import Autore_ArducaDiego, Libro_ArducaDiego
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

class AutoreDetailCBV(DetailView):
    model = Autore_ArducaDiego
    template_name = "autore.html"


class LibroListCBV(ListView):
    model = Libro_ArducaDiego
    template_name = "lista_libri.html"

news/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Articolo, Giornalista
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
# Create your views here.
def home(request):
   articoli = Articolo.objects.all()
   giornalisti = Giornalista.objects.all()
   context = {"articoli": articoli, "giornalisti": giornalisti}
   print(context)
   return render(request, "homepage.html",context)

def articoloDetailView(request, pk):
    # articolo = Articolo.objects.get(pk=pk)
    articolo = get_object_or_404(Articolo, pk=pk)
    context = {"articolo": articolo}
    return render(request, "articolo_detail.html",context)

class ArticoloDetailViewCB(DetailView):
    model = Articolo
    template_name = "articolo_detail.html"

class ArticoloListView(ListView):
    model = Articolo
    template_name = "lista_articoli.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["articoli"] = Articolo.objects.all()
        return context

class GiornalistaDetailViewCB(DetailView):
    model = Giornalista
    template_name = "giornalista_detail.html"


class GiornalistaListView(ListView):
    model = Giornalista
    template_name = "lista_giornalisti.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["giornalisti"] = Giornalista.objects.all()

        return context

prima_app/views.py
from django.http import HttpResponse
from django.shortcuts import render
# Create your views here.

#L1
def homepage(request):
    return HttpResponse("<h1>Ciao a tutti! Benvenuti nella homepage!</h1>")

#L2
def menu(request):
    return HttpResponse("<ol><li>Prima opzione</li><li>Seconda opzione</li><li>Terza opzione</li></ol>")

#L3
def chisiamo(request):
    return render(request, "chi_siamo.html")

#L4
def variabili(request):
    context= { 'var1': '10','var2': 'ciao', 'var3' : '123 hello world'}
    return render(request, "variabili.html",context)

#L5
def index(request):
    return render(request, "index.html")

seconda_app/views.py
from django.shortcuts import render
import datetime
# Create your views here.
#L6
def esempio_if(request):
    #https://www.decodejava.com/django-template-if-tag.htm
    #Creating a dictionary of key-value pairs
    dic = { 'var1' : 200,
    'var2' : 200,
    'var3' : 300 }
    #Calling the render() method to render the request from es_if.html page by using the dictionary, dic
    return render(request, "es_if.html", dic)

#L7
def esempio_ifelse(request):
    #https://www.decodejava.com/django-template-if-else-tag.htm
    dic = { 'var1' : 'admin',
    'var2' : 'admin',
    'var3' : 600 }
    return render(request, "es_ifelse.html", dic)

#L8
def esempio_elif(request):
    dic = { 'var1' : 100,
    'var2' : 100.0,
    'var3' : 100.50,
    'str1' : 'Hello',
    'str2' : 'hello',
    'str3' : "Hello",
    'list1': [1, datetime.date(2019,7,16), 'Make your life productive!'],
    'list2': [2, datetime.date(2019,7,16), 'Do not give up!']}
    return render(request, "es_ifelif.html", dic)

#L9
def esempio_for(request):
    #https://www.decodejava.com/django-template-for-tag.htm
    dic = { 'list1': [1, datetime.date(2019,7,16), 'Do not give up!'],'list2': [1, datetime.date(2019,7,16), 'Do not give up!'] }
    return render(request, "es_for.html", dic)

libreria/templates/autore.html
{% extends 'base.html' %}

{% block content %}
    <h1>Autore: {{ autore }} </h1>
    <br>
    {%for libro in autore.libri.all %}
        <h4><strong>Titolo: </strong>{{ libro.titolo }}</h4>
        <h4><strong>Autore: </strong>{%for genere in libro.genere.all %}{{ genere }} {% endfor %}</h4>
        <hr>
        
    {% endfor %}
{% endblock content %}

libreria/templates/base.html
<!doctype html>
<html lang="it">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Prova Pratica</title>
  </head>
  <body>
    <div> class="container"
        {% block content %}

        {% endblock content %}

    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>

libreria/templates/lista_libri.html
{% extends 'base.html' %}


{% block content %}
    <h1>La nostra libreria:</h1>
    <br>
    {%for libro in object_list %}
        <h4><strong>Titolo: </strong>{{ libro.titolo }}</h4>
        <h4><strong>Autore: </strong>{{ libro.autore }}</h4>
        <h4><strong>Genere: </strong>{%for genere in libro.genere.all %}{{ genere }} {% endfor %}</h4>
        <hr>
        
    {% endfor %}
{% endblock content %}

news/templates/articolo_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ articolo.titolo }}
{% endblock title %}

{% block content %}
    <h1>{{ articolo.titolo }}</h1>
    <h3>{{ articolo.contenuto }}</h3>
    <h5>Autore: {{ articolo.giornalista }}</h5>
{% endblock content %}

news/templates/giornalista_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ giornalista.nome }} + {{ giornalista.cognome }}
{% endblock title %}

{% block content %}
    <h1> {{ giornalista.nome }}  {{ giornalista.cognome }}</h1>
    
{% endblock content %}

news/templates/homepage.html
{% extends 'base.html'%}
{%block title%}
    Articoli e Giornalisti
{%endblock title%}
{%block content%}
<h4>Articoli:</h4>
    {% for articolo in articoli %}
        <p><strong>Titolo: </strong>{{ articolo.titolo }}</p>
        <p><strong>Contenuto: </strong>{{ articolo.contenuto }}</p>
        <p><strong>Autore: </strong>{{ articolo.giornalista }}</p>
        <hr>
    {% endfor %}
<h4>Giornalisti:</h4>
    {% for Giornalista in giornalisti %}
        <p><strong>Nome: </strong>{{ giornalista.nome }}</p>
        <p><strong>Cognome: </strong>{{ giornalista.cognome }}</p>
        <hr>
    {% endfor %}
{%endblock content%}
       

news/templates/lista_articoli.html
{% extends 'base.html' %}

{% block title %}
    Lista Articoli
{% endblock title %}

{% block content %}
    <h4>Articoli:</h4>
    {% for articolo in articoli %}
        <p><strong>Titolo:</strong><a href="/news/articoli/{{ articolo.id}}">{{ articolo.titolo }}</a></p>
        <p><strong>Contenuto: </strong>{{ articolo.contenuto }}</p>
        <p><strong>Autore: </strong>{{ articolo.giornalista }}</p>
        <hr>
    {% endfor %}
    
{% endblock content %}

news/templates/lista_giornalisti.html
{% extends 'base.html' %}

{% block title %}
    Lista Giornalisti
{% endblock title %}

{% block content %}
    <h4>Giornalisti:</h4>
    {% for gio in giornalista %}
        <p><strong>Nome:</strong><a href="/news/giornalisti/{{ giornalista.id}}">{{ gio.nome }}</a></p>
        <p><strong>Cognome: </strong>{{ gio.cognome }}</p>
       
        <hr>
    {% endfor %}
    
{% endblock content %}

prima_app/templates/chi_siamo.html
{% extends 'base.html'%}
{%block title%}
	{{block.super}} | Chi siamo
{%endblock title%}

{%block content%}
    <h3>Siamo quelli che siamo ?</h3>
{%endblock content%}

prima_app/templates/index.html
{% extends 'base.html'%}
{%block title%}
	{{block.super}} | Chi siamo
{%endblock title%}

{%block content%}
<ol><li><a href="{% url 'prima_app:index'%}">index</a></li>
    <li><a href="{% url 'prima_app:home'%}">home page welcome</a></li>
    <li><a href="{% url 'prima_app:menu'%}">menu</a></li>
    <li><a href="{% url 'prima_app:chisiamo'%}">chi siamo</a></li>
    <li><a href="{% url 'prima_app:variabili'%}">variabili</a></li>
</ol>
{%endblock content%}

prima_app/templates/variabili.html
{% extends 'base.html'%}
{%block title%}
	{{block.super}} | Chi siamo
{%endblock title%}

{%block content%}
<ol>
    <li> {{ var1 }}</li>
    <li> {{ var2 }}</li>
    <li> {{ var3 }}</li>
</ol>
{%endblock content%}

seconda_app/templates/es_for.html
{% extends 'base.html'%}
{%block title%}
	{{block.super}} | Chi siamo
{%endblock title%}

{%block content%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>for</title>
</head>
<body>
Looping over a sequence of items using <b>forloop.counter</b> variable:
	<br/>
	{% for x in list2 %}
		<i>{{ forloop.counter }} </i> : {{ x }}<br>
	{% endfor %}
	<br/>


	Looping over a sequence of items using <b>forloop.counter0</b> variable:
	<br/>
	{% for x in list2 %}
		<i>{{ forloop.counter0 }}</i> : {{ x }}<br/>
	{% endfor %}
	<br/>


	Printing the first element of sequence using <b>forloop.first</b> variable:
	<br/>
	{% for x in list2 %}
		{% if forloop.first %}
			<i>The first item</i> - {{ x }}
		{% endif%}
	{% endfor %}
	<br/>
	<br/>


	Printing the last element of sequence using <b>forloop.last</b> variable:
	<br/>
	{% for x in list2 %}
		{% if forloop.last %}
			<i>The last item</i> - {{ x }}
		{% endif%}
	{% endfor %}
	<br/>
	<br/>


	Printing the left over items in the sequence using <b>forloop.revcounter</b> variable:
	<br/>
	{% for x in list2 %}
		<i>Total number of leftover item to be iterated</i> - {{ forloop.revcounter }}<br/>
		<i>Item</i> - {{ x }}<br/>
	{% endfor %}
	<br/>


	Printing the left over items in the sequence using <b>forloop.revcounter0</b> variable:
	<br/>
	{% for x in list2 %}
		<i>Total number of leftover item to be iterated</i> - {{ forloop.revcounter0 }}<br/>
		<i>Item</i> - {{ x }}<br/>
	{% endfor %}
	<br/>


	Printing the reversed sequence of items using <b>reversed</b> attribute of <b>for</b> tag: <br/>
	{% for x in list2 reversed %}
		<i>Item</i> - {{ x }}<br/>
	{% endfor %}
</body>
</html>
{%endblock content%}

seconda_app/templates/es_if.html
{% extends 'base.html'%}
{%block title%}
	{{block.super}} | Chi siamo
{%endblock title%}

{%block content%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>if</title>
</head>
<body>
	<b>var1 = {{ var1 }}</b> <br/>
	<b>var2 = {{ var2 }}</b> <br/>
	<b>var3 = {{ var3 }}</b> <br/>


	{% if var1 < var2 %}
		<p><i>var1 is smaller than var2 </i></p>
	{% endif %}


	{% if var1 > var2 %}
		<p><i>var1 is greater than var2 </i></p>
	{% endif %}


	{% if var1 <= var2 %}
		<p><i>var1 is less than or equal to var2 </i></p>
	{% endif %}


	{% if var1 >= var2 %}
		<p><i>var1 is greater than or equal to var2 </i></p>
	{% endif %}


	{% if var1 == var2 %}
		<p><i>var1 is equal to var2 </i></p>
	{% endif %}


	{% if var1 != var2 %}
		<p><i>var1 is not equal to var2 </i></p>
	{% endif %}


	{% if var1 < var2 and var1 < var3 %}
		<p><i>var1 is less than var2 and var1 is less than var3 </i></p>
	{% endif %}


	{% if var1 < var2 or var3 < var2 %}
		<p><i>var1 is less than var2 or var3 is less than var2 </i></p>
	{% endif %}


	{% if not var1 > var2 %}
		<p><i>var1 is not greater than var2 </i></p>
	{% endif %}
</body>
</html>
{%endblock content%}

seconda_app/templates/es_ifelse.html
{% extends 'base.html'%}
{%block title%}
	{{block.super}} | Chi siamo
{%endblock title%}

{%block content%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>if else</title>
</head>
<body>
<b>var1 = {{ var1 }}</b> <br/>
	<b>var2 = {{ var2 }}</b> <br/>
	<b>var3 = {{ var3 }}</b> <br/>


	{% if var1 < var2 %}
		<p><i>var1 is smaller than var2 </i></b>
	{% else %}
		<p><i>var1 is not smaller than var2 </i></b>
	{% endif %}


	{% if var1 > var2 %}
		<p><i>var1 is greater than var2 </i></p>
	{% else %}
		<p><i>var1 is not greater than var2 </i></p>
	{% endif %}


	{% if var1 <= var2 %}
		<p><i>var1 is less than or equal to var2 </i></p>
	{% else %}
		<p><i>var1 is not less than or not equal to var2 </i></p>
	{% endif %}


	{% if var1 >= var2 %}
		<p><i>var1 is greater than or equal to var2 </i></p>
	{% else %}
		<p><i>var1 is not greater than or not equal to var2 </i></p>
	{% endif %}


	{% if var1 == var2 %}
		<p><i>var1 is equal to var2 </i></p>
	{% else %}
		<p><i>var1 is not equal to var2 </i></p>
	{% endif %}


	{% if var1 != var2 %}
		<p><i>var1 is not equal to var2 </i></p>
	{% else %}
		<p><i>var1 is equal to var2 </i></p>
	{% endif %}


	{% if var1 < var2 and var1 < var3 %}
		<p><i>var1 is less than var2 and var1 is less than var3 </i></p>
	{% else %}
		<p><i>var1 is not less than var2 and var1 is not less than var3 </i></p>
	{% endif %}


	{% if var1 < var2 or var3 < var2 %}
		<p><i>var1 is less than var2 or var3 is less than var2 </i></p>
	{% else %}
		<p><i>var1 is not less than var2 or var3 is not less than var2 </i></p>
	{% endif %}


	{% if not var1 > var2 %}
		<p><i>var1 is not greater than var2 </i></p>
	{% else %}
		<p><i>var1 is greater than var2 </i></p>
	{% endif %}


	{% if a != a %}
		 <i>a is not equal to a </i></b>
	{% else %}
		 <i>a is equal to a </i></b>
	{% endif %}


	{% if 'hi' != 'hi' %}
		 <i>hi is not equal to hi </i></b>
	{% else %}
		 <i>hi is equal to hi </i></b>
	{% endif %}


	{% if 'hello world' != "hello world" %}
		 <i>hello world is not equal to hello world </i></b>
	{% else %}
		 <i>hello world is equal to hello world </i></b>
	{% endif %}


	{% if zero == 0 %}
		 <i>zero is equal to 0 </i></b>
	{% else %}
		 <i>zero is not equal to 0</i></b>
	{% endif %}
</body>
</html>
{%endblock content%}

templates/base.html
{%load static%}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>{% block title %} My project {% endblock title %}</title>
  </head>
  <body>
    {% block navbar %} 
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
           
            
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                prima_app
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'prima_app:index' %}">Index</a>
                        <a class="dropdown-item" href="{% url 'prima_app:home' %}">Home</a>
                        <a class="dropdown-item" href="{% url 'prima_app:chisiamo' %}">Chi siamo</a>
                        <a class="dropdown-item" href="{% url 'prima_app:variabili' %}">Variabili</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                seconda_app
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'seconda_app:if' %}">Ifs</a>
                        <a class="dropdown-item" href="{% url 'seconda_app:ifelse' %}">If else</a>
                        <a class="dropdown-item" href="{% url 'seconda_app:elif' %}">If elif</a>
                        <a class="dropdown-item" href="{% url 'seconda_app:for' %}">for</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                news
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'news:lista_articoli' %}">Articoli</a>
                        <a class="dropdown-item" href="{% url 'news:lista_giornalisti' %}">Giornalisti</a>
                        
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                libreria
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'libreria:autore' %}">Autore</a>
                        <a class="dropdown-item" href="{% url 'libreria:lista_libri' %}">Libri</a>
                        
              </div>
            </li>
            
          
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
    {% endblock navbar %}
    <div class='container'> 
    {%block content%} 
    {%endblock content%}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>